openapi: 3.0.0
info:
  title: Translation API
  description: API for content translation in the Physical AI & Humanoid Robotics Textbook
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /api/translate:
    post:
      summary: Translate content
      description: Translate textbook content from English to Urdu
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslationRequest'
      responses:
        '200':
          description: Translation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranslationResponse'
        '400':
          description: Invalid translation request
        '500':
          description: Server error

  /api/translate/toggle:
    post:
      summary: Toggle translation preference
      description: Set user's preferred language for content display
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LanguagePreference'
      responses:
        '200':
          description: Language preference updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LanguagePreference'
        '400':
          description: Invalid language preference
        '401':
          description: Unauthorized
        '500':
          description: Server error

  /api/translate/cache/clear:
    post:
      summary: Clear translation cache
      description: Clear cached translations for specific content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CacheClearRequest'
      responses:
        '200':
          description: Cache cleared successfully
        '400':
          description: Invalid cache clear request
        '401':
          description: Unauthorized
        '500':
          description: Server error

components:
  schemas:
    TranslationRequest:
      type: object
      required:
        - content
        - target_language
      properties:
        content:
          type: string
          description: Content to translate
        target_language:
          type: string
          description: Target language code (e.g., 'ur' for Urdu)
          default: 'ur'
        source_language:
          type: string
          description: Source language code (e.g., 'en' for English)
          default: 'en'
        content_type:
          type: string
          enum: [text, chapter, paragraph, term]
          description: Type of content being translated

    TranslationResponse:
      type: object
      properties:
        original_content:
          type: string
          description: The original content that was translated
        translated_content:
          type: string
          description: The translated content
        detected_language:
          type: string
          description: The detected source language
        target_language:
          type: string
          description: The requested target language
        translation_quality_score:
          type: number
          format: float
          minimum: 0
          maximum: 1
          description: Quality score for the translation (0-1)
        technical_terms_preserved:
          type: array
          items:
            $ref: '#/components/schemas/TechnicalTerm'
          description: Technical terms preserved with Urdu explanations

    TechnicalTerm:
      type: object
      properties:
        english_term:
          type: string
          description: Original English technical term
        urdu_translation:
          type: string
          description: Urdu translation of the term
        explanation:
          type: string
          description: Urdu explanation of the technical term

    LanguagePreference:
      type: object
      required:
        - language
      properties:
        language:
          type: string
          enum: [en, ur]
          description: Preferred language code
        user_id:
          type: string
          format: uuid
          description: Optional user identifier for authenticated users

    CacheClearRequest:
      type: object
      properties:
        content_id:
          type: string
          description: Identifier for the content to clear from cache
        content_type:
          type: string
          description: Type of content to clear
        all:
          type: boolean
          description: Whether to clear all cached translations