/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Physical AI & Humanoid Robotics Textbook",
  "tagline": "Interactive textbook on Physical AI and Humanoid Robotics with AI-powered learning support",
  "favicon": "img/favicon.ico",
  "url": "https://agentic-ai.github.io",
  "baseUrl": "/physical-AI-humanoid-robotics/",
  "organizationName": "agentic-ai",
  "projectName": "physical-AI-humanoid-robotics",
  "deploymentBranch": "gh-pages",
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "ur"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/mnt/c/Users/finance01/Documents/WD/agentic-ai/specify-plus/hackathon-dec25/physical-AI-humanoid-robotics/frontend/sidebars.js",
          "editUrl": "https://github.com/agentic-ai/physical-AI-humanoid-robotics/edit/main/",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true
        },
        "blog": false,
        "theme": {
          "customCss": "/mnt/c/Users/finance01/Documents/WD/agentic-ai/specify-plus/hackathon-dec25/physical-AI-humanoid-robotics/frontend/src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "textbook",
        "path": "docs",
        "routeBasePath": "textbook",
        "sidebarPath": "/mnt/c/Users/finance01/Documents/WD/agentic-ai/specify-plus/hackathon-dec25/physical-AI-humanoid-robotics/frontend/sidebars.js"
      }
    ]
  ],
  "themeConfig": {
    "image": "img/textbook-social-card.jpg",
    "navbar": {
      "title": "Physical AI & Humanoid Robotics",
      "logo": {
        "alt": "Physical AI & Humanoid Robotics Textbook",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Textbook Chapters"
        },
        {
          "to": "/textbook/intro",
          "label": "Textbook",
          "position": "left"
        },
        {
          "to": "/api-reference",
          "label": "API",
          "position": "left"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://github.com/agentic-ai/physical-AI-humanoid-robotics",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Textbook",
          "items": [
            {
              "label": "Introduction",
              "to": "/textbook/intro"
            },
            {
              "label": "Physical AI Basics",
              "to": "/textbook/physical-ai-basics"
            },
            {
              "label": "Humanoid Robotics",
              "to": "/textbook/humanoid-robotics"
            },
            {
              "label": "Advanced Topics",
              "to": "/textbook/advanced-topics"
            }
          ]
        },
        {
          "title": "Features",
          "items": [
            {
              "label": "AI-Powered Chatbot",
              "to": "/textbook/intro#chatbot"
            },
            {
              "label": "Personalized Learning",
              "to": "/textbook/intro#personalization"
            },
            {
              "label": "Urdu Translation",
              "to": "/textbook/intro#translation"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub Discussions",
              "href": "https://github.com/agentic-ai/physical-AI-humanoid-robotics/discussions"
            },
            {
              "label": "Issues",
              "href": "https://github.com/agentic-ai/physical-AI-humanoid-robotics/issues"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Agentic AI. Built with Docusaurus for the Physical AI & Humanoid Robotics Textbook."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "python",
        "javascript",
        "json",
        "bash"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "algolia": {
      "appId": "YOUR_ALGOLIA_APP_ID",
      "apiKey": "YOUR_ALGOLIA_API_KEY",
      "indexName": "physical-ai-humanoid-robotics",
      "contextualSearch": true,
      "externalUrlRegex": "external\\.com|domain\\.com",
      "replaceSearchResultPathname": {
        "from": "/docs/",
        "to": "/textbook/"
      },
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
